config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :orders do
        get :list
        match "/list/:shipment_id" => "orders#list", :as =>"shipments_picking_list"
      end
    end
  end
end

app/controllers/spree/admin/orders_controller_decorator.rb
Spree::Admin::OrdersController.class_eval do
  def list
    @order = Spree::Order.find_by_number! params[:order_id]
    @shipment ||= @order.shipments.find_by_number(params[:shipment_id])
  end
end

app/controllers/spree/admin/shipments_controller_decorator.rb
#Spree::Admin::ShipmentsController.class_eval do
  #def list
    #@order = Spree::Order.find_by_number! params[:order_id]
    #@shipment ||= @order.shipments.find_by_number(params[:shipment_id])
  #end
#end

app/views/spree/admin/orders/list.html.erb
<% content_for :page_title do %>
  <%= t(:order) %> #<%= @order.number %> <i class="icon-arrow-right"></i> <%= t(:shipments) %> <i class="icon-arrow-right"></i> #<%= @shipment.number%> (<%= t(@shipment.state.to_sym, :scope => :shipment_states, :default => @shipment.state.to_s.humanize) %>)
<% end %>
<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_order), admin_order_url(@order.number), :icon => 'icon-arrow-left' %></li>
<% end %>

<div id="picking_list">
  <h3><%= t(:shipping_list) %></h3>
  <div id="order-info" data-hook class="row">
    <fieldset class="alpha eight columns no-border-bottom">
      <legend align="center"><%= t(:ship_address) %></legend>
      <div class="align-center">
        <div data-hook="address"><%= @order.ship_address.to_s %></div>
      </div>
    </fieldset>
    <fieldset class="alpha eight columns no-border-bottom">
      <legend align="center"><%= t(:completed_at) %></legend>
      <div class="align-center">
        <div data-hook="date"><%= @order.completed_at %></div>
      </div>
    </fieldset>
  </div>
  <table class="index" data-hook="order_details">
    <thead id="line-items" data-hook>
      <tr data-hook="order_details_line_items_headers">
        <th class="description"><%= t(:item_description) %></th>
        <th class="sku"><%= t(:sku) %></th>
        <th class="qty"><%= t(:qty) %></th>
        <th class="location"><%= t(:location) %></th>
      </tr>
    </thead>
    <tbody>
      <% parents = @shipment.line_items.reject{|l| l.parent_id.present?} %>
      <% parents.each_with_index do |item, index| %>
        <tr data-hook="order_details_line_item_row" class="<%= cycle('odd', 'even')%>">
          <td width="300"><%= item.variant.product.name %> <%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %></td>
          <td><%= item.variant.sku %></td>
          <td class="qty"><%= item.quantity %></td>
          <td class="location"><%= item.variant.location %></td>
        </tr>
        <% item.child_items.each_with_index do |c, i| %>
          <tr data-hook="order_details_line_item_row" class="<%= cycle('odd', 'even')%>">
            <td width="300">---<%= c.variant.product.name %> <%= "(" + variant_options(c.variant) + ")" unless c.variant.option_values.empty? %></td>
            <td><%= c.variant.sku %></td>
            <td class="qty"><%= c.quantity %></td>
            <td class="location"><%= c.variant.location %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>